# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DbUPme0Zsrh1JMI8UQC0vF3uOhBPjye
"""

!pip install pygal_maps_world

!pip install cairosvg

from pygal.style import Style

custom_style = Style(colors=['darkgreen'])
worldmap = pygal.maps.world.World(style = custom_style)
worldmap.title = "Top 5 countries with the most Starbucks stores"
worldmap.add('stores',{
    'us' : 16346,
    'cn' : 6804,
    'kr' : 1870,
    'jp' : 1733,
    'ca' : 1458
})



import pygal
worldmap = pygal.maps.world.World()
worldmap.add('stores',{
    'us' : 16346,
    'cn' : 6804,
    'kr' : 1870,
    'jp' : 1733,
    'ca' : 1458
})

import matplotlib.pyplot as plt
import geopandas as gpd





world = gpd.read_file(gpd.datasets.get_path("naturalearth_lowres"))

fig = plt.figure(figsize = (20,10))
ax = fig.add_subplot()
world.plot(
    ax=ax,
    color = "lightgray",
    edgecolor = "black"

)

ax.set_xticks([])
ax.set_yticks([])

plt.title("Example of world map by geopandas")
plt.show()

north_america = world[world['continent'] == "North America"]

world['continent'].value_counts()

usa = north_america[north_america["name"]=="United state of America"]



