# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iIrE3YJPzSK5plwIUo-33ycLy0VArU3s
"""

import matplotlib.pyplot as plt
x = [1, 2 ,3, 4, 5]
y = [5, 10, 15, 20, 25]
plt.plot(x, y)
plt.show()

import matplotlib.pyplot as plt
data = [5, 20, 10, 15 ,10]
plt.plot(data)
plt.show()

import matplotlib.pyplot as plt
data = [50, 10, 30, 15, 40]
plt.plot(data)
plt.show()

y = [5, 20, 10, 15 ,10 ]
x = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
plt.xlabel('Day')
plt.ylabel('Y')
plt.plot(x, y ,color='r')
plt.show()

y = [40, 20, 50, 30 ,10 ]
x = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
plt.xlabel('Day')
plt.ylabel('Y')
plt.plot(x, y ,color='m')
plt.show()

x = [1, 2 ,3, 4, 5]
y = [5, 10, 15, 20, 25]

plt.plot(x, y , ls = '--', color='m')
plt.show()

x = [1, 2 ,3, 4, 5]
y = [5, 15, 15, 20, 10]
plt.plot(x, y , 'cd--', color='c')
plt.show()

y = [50, 70, 35, 90, 40]
x = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
plt.bar(x, y)
plt.xticks(rotation=45)
plt.show()

y = [20, 50, 40, 90, 70]
x = ['Aug', 'Sep', 'Oct', 'Nov', 'Dec']
plt.bar(x, y)
plt.xticks(rotation=45)
plt.show()

y = [20, 50, 40, 90, 70]
x = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri']
plt.barh(x, y , color='c', hatch='// \\')
plt.show()

data = [35, 20, 25, 5 ,15]
lb=['Kerry', 'Flash', 'j&T', 'DHL','Thailand Post']
plt.pie(data,labels=lb, autopct="%.0f%%", colors=['red','yellow','blue','lightgreen','green'])
plt.show()

data = [35, 20, 25, 5 ,15]
lb=['Kerry', 'Flash', 'j&T', 'DHL','Thailand Post']
explode = [0, 0.1, 0 ,0.2, 0]
plt.pie(data, labels=lb, explode=explode,startangle =90, colors=['red','yellow','blue','lightgreen','green'] ,shadow=True,autopct="%.1f%%")
plt.show()

import random
a = random.random()
print('a =', a)

import random
b = random.uniform(1.5,5.5)
print('b =', b)

import random
d = random.choice(['ant', 'bird', 'cat', 'dog'])
print('d =', d)

a= randim

import random