# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JNgJFnLhFyYc2zmnJCxQLGqia2PwadJp
"""

from datetime iทport
#Object : variables : Methods

class Account :
  def __init__(self, numID  ):
    self.number = numID
    def ____(self, numID  ):
      self.number =  numID
      self.account_type()

    def account_type(self):

      if str(self.number ).startswith("1"):
        self.type = "current"
      elif str(self.number ).startswith("2"):
        self.type = "saving"

    def interest_rate(self):

      if self.type == "current" :
        self.interest = 0
      elif self.type == "saving" :
        self.interest = 5

      return self.interest
    def interest_rate()
    self.balance = 1000

    current

acc = Account(1001)

acc.type

acc.interest

acc.interest_rate()

acc.interest_accrued()

acc

#import library

#numpy

import numpy as np

np.zeros(10)

import pandas as pd

import numpy
numpy.zeros(10)

from numpy import zeros

zeros(5)

from numpy import library

